template: external-service
values:
    fqdn: cribbage.cloud
    image: krakenapps.azurecr.io/rust_cribbage_core:noel
    app: cribbage-api
    cpu: 0.5 
    memory: 64M
    replicas: 2
    port: 8080
